# Generated by Django 2.2.4 on 2020-09-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200918_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='worked_on',
            field=models.BooleanField(default=False),
        ),
    ]
