# Generated by Django 2.2.4 on 2020-09-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200918_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='electrical',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='garden',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='pet_care',
        ),
        migrations.AddField(
            model_name='jobs',
            name='category',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
